package org.studiomexx.clitical_android.ui.theme

import androidx.compose.ui.graphics.Color

val JsvsColor = Color(0xFF2D6A7B)

// Generated from ColorScheme.fromSeed(seedColor: jsvsColor) in the clti_risk
// Flutter app, so both apps render the identical Material 3 palette.
val LightPrimary = Color(0xFF00677C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB1EBFF)
val LightOnPrimaryContainer = Color(0xFF004E5E)
val LightSecondary = Color(0xFF4B626A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE7F0)
val LightOnSecondaryContainer = Color(0xFF344A51)
val LightTertiary = Color(0xFF585C7E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDFE0FF)
val LightOnTertiaryContainer = Color(0xFF404565)
val LightBackground = Color(0xFFF5FAFD)
val LightOnBackground = Color(0xFF171C1E)
val LightSurface = Color(0xFFF5FAFD)
val LightOnSurface = Color(0xFF171C1E)
val LightSurfaceVariant = Color(0xFFDBE4E7)
val LightOnSurfaceVariant = Color(0xFF40484B)
val LightOutline = Color(0xFF70787C)
val LightOutlineVariant = Color(0xFFBFC8CB)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F4F5)
val LightSurfaceContainer = Color(0xFFEDEEEF)
val LightSurfaceContainerHigh = Color(0xFFE7E8E9)
val LightSurfaceContainerHighest = Color(0xFFE1E3E4)
val LightSurfaceDim = Color(0xFFD9DADB)
val LightSurfaceBright = Color(0xFFF8F9FB)

val DarkPrimary = Color(0xFF86D1E9)
val DarkOnPrimary = Color(0xFF003642)
val DarkPrimaryContainer = Color(0xFF004E5E)
val DarkOnPrimaryContainer = Color(0xFFB1EBFF)
val DarkSecondary = Color(0xFFB2CAD3)
val DarkOnSecondary = Color(0xFF1D343B)
val DarkSecondaryContainer = Color(0xFF344A51)
val DarkOnSecondaryContainer = Color(0xFFCEE7F0)
val DarkTertiary = Color(0xFFC1C4EB)
val DarkOnTertiary = Color(0xFF2A2E4D)
val DarkTertiaryContainer = Color(0xFF404565)
val DarkOnTertiaryContainer = Color(0xFFDFE0FF)
val DarkBackground = Color(0xFF0F1416)
val DarkOnBackground = Color(0xFFDEE3E6)
val DarkSurface = Color(0xFF0F1416)
val DarkOnSurface = Color(0xFFDEE3E6)
val DarkSurfaceVariant = Color(0xFF40484B)
val DarkOnSurfaceVariant = Color(0xFFBFC8CB)
val DarkOutline = Color(0xFF8A9295)
val DarkOutlineVariant = Color(0xFF40484B)
val DarkSurfaceContainerLowest = Color(0xFF0C0F10)
val DarkSurfaceContainerLow = Color(0xFF191C1D)
val DarkSurfaceContainer = Color(0xFF1D2021)
val DarkSurfaceContainerHigh = Color(0xFF272A2C)
val DarkSurfaceContainerHighest = Color(0xFF323536)
val DarkSurfaceDim = Color(0xFF111415)
val DarkSurfaceBright = Color(0xFF373A3B)
