package org.studiomexx.clitical_android.ui.theme

import androidx.compose.ui.graphics.Color

val JsvsColor = Color(0xFF2D6A7B)

val LightPrimary = Color(0xFF00687B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFAFEFFF)
val LightOnPrimaryContainer = Color(0xFF001F26)
val LightSecondary = Color(0xFF4B6269)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE7EF)
val LightOnSecondaryContainer = Color(0xFF061E24)
val LightTertiary = Color(0xFF575C7E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDEE1FF)
val LightOnTertiaryContainer = Color(0xFF131937)
val LightBackground = Color(0xFFFBFCFD)
val LightOnBackground = Color(0xFF191C1D)
val LightSurface = Color(0xFFFBFCFD)
val LightOnSurface = Color(0xFF191C1D)

val DarkPrimary = Color(0xFF59D5FA)
val DarkOnPrimary = Color(0xFF003641)
val DarkPrimaryContainer = Color(0xFF004E5D)
val DarkOnPrimaryContainer = Color(0xFFAFEFFF)
val DarkSecondary = Color(0xFFB2CBD3)
val DarkOnSecondary = Color(0xFF1D343A)
val DarkSecondaryContainer = Color(0xFF334A51)
val DarkOnSecondaryContainer = Color(0xFFCEE7EF)
val DarkTertiary = Color(0xFFBFC4EB)
val DarkOnTertiary = Color(0xFF282E4D)
val DarkTertiaryContainer = Color(0xFF3F4565)
val DarkOnTertiaryContainer = Color(0xFFDEE1FF)
val DarkBackground = Color(0xFF191C1D)
val DarkOnBackground = Color(0xFFE1E3E4)
val DarkSurface = Color(0xFF191C1D)
val DarkOnSurface = Color(0xFFE1E3E4)